# only one epoch, and two random trials

###### directory where results will be written
output_dir: ./results/

###### experiment time limit in seconds
experiment_time_limit: 300
trial_time_limit: 100

###### number of trials for hyperparameter search & optimization
n_random_trials: 0
n_opt_trials: 5
hparam_seed: 0

###### GPU parameters
use_gpu: False
gpu_ids: [0]
data_parallel: True

###### Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 2
epochs: 1
logging_period: 100
